version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: MaterialDesignColors
    versions:
    - 2.0.0
  - dependency-name: MahApps.Metro
    versions:
    - 2.4.4
  - dependency-name: MaterialDesignThemes
    versions:
    - 4.0.0
  - dependency-name: Prism.Wpf
    versions:
    - 8.0.0.1909
